### ISSUE TITLE
Shopware throws an error right after installation

### ISSUE THREAD

**Issue by 4typen** [shyim/whoops-for-shopware#2]
Hi there,

I'm trying to use this plugin. Therefore i installed the latest release zip (1.1.0). After the activation shopware throws an error. Both in the frontend and in the backend. See:

`
Fatal error: Uncaught Error: Class 'Whoops\Run' not found in /home/vagrant/www/shopware/custom/plugins/WhoopsForShopware/WhoopsForShopware.php:30 Stack trace: #0 /home/vagrant/www/shopware/engine/Library/Enlight/Event/Handler/Default.php(91): WhoopsForShopware\WhoopsForShopware->onRouteStartup(Object(Enlight_Controller_EventArgs)) #1 /home/vagrant/www/shopware/custom/plugins/ShyimProfiler/Components/Event/EventManager.php(258): Enlight_Event_Handler_Default->execute(Object(Enlight_Controller_EventArgs)) #2 /home/vagrant/www/shopware/custom/plugins/ShyimProfiler/Components/Event/EventManager.php(78): ShyimProfiler\Components\Event\EventManager->parentNotify('Enlight_Control...', Object(Enlight_Controller_EventArgs)) #3 /home/vagrant/www/shopware/engine/Library/Enlight/Controller/Front.php(157): ShyimProfiler\Components\Event\EventManager->notify('Enlight_Control...', Object(Enlight_Controller_EventArgs)) #4 /home/vagrant/www/shopware/engine/Shopware/Kernel.php(182): Enlight_Controller_Front->dispatch() #5 /home/vagrant/www in /home/vagrant/www/shopware/custom/plugins/WhoopsForShopware/WhoopsForShopware.php on line 30`

**Comment by uehler** [comment]
you have to run `composer install` in the directory of the plugin

**Comment by shyim** [comment]
In the last version was a mistake with the composer autoloading. I fixed the issue and made a new release. Could you try this?
https://github.com/shyim/whoops-for-shopware/releases/download/1.1.1/WhoopsForShopware-1.1.1.zip

**Comment by 4typen** [comment]
Thanks, now it works!
